### ISSUE TITLE
When to support the latest Ad astra version

### ISSUE THREAD

**Issue by moguang2004** [DRD2k8/ad_extendra#1]
I like your mod, could you please tell me that when do you plan to update it to support the latest version of Ad astra?

**Comment by DRD2k8** [comment]
Maybe if I figure out how to make the planet orbits on the screen because in 1.15.7 and up, you can't do dynamic resources for that. So we'll see.

**Comment by DRD2k8** [comment]
The mod is now available for the latest Ad Astra version

https://modrinth.com/mod/ad_extendra-continuation/version/1.1.0

**Comment by moguang2004** [comment]
> The mod is now available for the latest Ad Astra version
> 
> https://modrinth.com/mod/ad_extendra-continuation/version/1.1.0

Thanks for anouncing me!

**Comment by DRD2k8** [comment]
You're welcome.
