### ISSUE TITLE
[Bug report]: Mixin Crash

### ISSUE THREAD

**Issue by Mysticpasta1** [DRD2k8/ad_extendra#10]
### Describe the bug

it crashed on startup

### Steps to reproduce

run ad extendra

### Expected Behaviour

no crashing

### Logs

https://gist.github.com/Mysticpasta1/76f6311d31c5ab4434c041a98c0773f8

### Minecraft Version

1.20.1

### Mod Loader

Forge

### Mod Version

1.1.1

### Additional context

ad astra is 1.15.19

**Comment by DRD2k8** [comment]
This will be fixed in 1.1.2 which will be for Ad Astra 1.15.19.

**Comment by Mysticpasta1** [comment]
how fast will it be on CF
