### ISSUE TITLE
[Feature request]: Add More Planets And Moons

### ISSUE THREAD

**Issue by mZiyadhbinismail** [DRD2k8/ad_extendra#13]
### Is your feature request related to a problem?

Plz Add More Planets and his Moons

### Describe the solution you'd like

Nope

### Minecraft Version

No Version

### Mod Loader

Both

### Mod Version

No Mod Version

**Comment by DRD2k8** [comment]
I will do that soon in version 1.1.3.

**Comment by mZiyadhbinismail** [comment]
OMG
