### ISSUE TITLE
[Bug report]: There is a serious crash issue with Ad Astra!: Giselle Addon

### ISSUE THREAD

**Issue by xiaojuzi122** [DRD2k8/ad_extendra#14]
### Describe the bug

When placing a rocket above level 5, you can put an Ad Astra!: Giselle Addon's Fuel Loader game crashes when you put it next to it
This is the output from the server side:
[latest.log](https://github.com/user-attachments/files/18020480/latest.log)

### Logs

[latest.log](https://github.com/user-attachments/files/18020383/latest.log)

### Minecraft Version

1.20.1

### Ad Astra Version

1.15.19

### Mod Loader

Forge

### Mod Version

1.1.2

**Comment by DRD2k8** [comment]
I made a [commit](https://github.com/DRD2k8/ad_extendra/commit/b3753051fee9f8bb04e29cc7e21b5fd41e84e4f9) so we'll see if this fixes the issue once 1.1.3 of this mod comes out.
