### ISSUE TITLE
Version incompatibility

### ISSUE THREAD

**Issue by Oregano1963** [DRD2k8/ad_extendra#3]
The latest version released crashes saying it requires ad astra 1.15.5 when 1.15.18 is the latest release.

**Comment by JeshMate** [comment]
> The latest version released crashes saying it requires ad astra 1.15.5 when 1.15.18 is the latest release.

yeah that simply means that you need 1.15.5 exactly, like it says at the very bottom of the mod info page, you cant use the latest afaik

**Comment by DRD2k8** [comment]
Well, you need Ad Astra version 1.15.5 for this mod's versions. Version 1.1.0 of this mod will start supporting for version 1.15.18. But it might be for when version 1.15.19 of Ad Astra comes out, which is expected to fix hundreds of issues and re-add the JSON APIs for the planet screen. Unfortunately, Ad Astra hasn't updated in an extremely long time.

**Comment by DRD2k8** [comment]
Check out the [status](https://github.com/DRD2k8/ad_extendra/wiki/Status) of the mod to see it for versions 1.20.1-1.15.18+.
