### ISSUE TITLE
can't land on planets with tier higher than 4

### ISSUE THREAD

**Issue by Mysticpasta1** [DRD2k8/ad_extendra#4]
when trying to go to mars in a tier 5 rocket in my modpack it froze kinda, the world still generate but the rocket and player wouldn't fall to the ground at all. 

temp fix was to tp the y current location up 100 y, this resulted in the rocket and player falling again, all planets seem to have the same issue, and all rocket above tier 4 (those added by the addon) have the issue.

for more information contact me @MysticPasta1 on discord or through my discord server on my profile

**Comment by Mysticpasta1** [comment]
actually it seems it was just mars having the issues

**Comment by DRD2k8** [comment]
What other mods do you have installed?

**Comment by Mysticpasta1** [comment]
I also tested with ad ad astra and this mod by themselves too, still seems to happen

**Comment by DRD2k8** [comment]
Well, when I went to mars with the Tier 5 rocket, it seemed to work just fine for me. Anything else about why this won't work for you?

**Comment by Mysticpasta1** [comment]
that is strange

it might be another mod then

**Comment by Mysticpasta1** [comment]
can you add me on discord I want to show you my screen

**Comment by Mysticpasta1** [comment]
I have about 1000 mods in my modpack

**Comment by Mysticpasta1** [comment]
so I need help ruling out what it could be

**Comment by DRD2k8** [comment]
Well, I might keep this issue open until I find out why this happens. I think the 1000 mods might be the reason it froze.

**Comment by Mysticpasta1** [comment]
![image](https://github.com/user-attachments/assets/4da712bb-e253-4c93-a83f-31f880d72451)
I also have these

**Comment by DRD2k8** [comment]
Ok

**Comment by Mysticpasta1** [comment]
it was one of these
proxima plus
extra additions
distance horizons

**Comment by Mysticpasta1** [comment]
removing them fixes the issue :D
