### ISSUE TITLE
Failure message: Mod ad_extendra requires ad_astra 1.15.5 21:53:15.954 game Currently, ad_astra is 1.15.18

### ISSUE THREAD

**Issue by Mysticpasta1** [DRD2k8/ad_extendra#5]
solution update the ad astra dep to 1.15.18

**Comment by Mysticpasta1** [comment]
the ad astra delight mod and giselle addon both require 1.15.18

**Comment by DRD2k8** [comment]
> the ad astra delight mod and giselle addon both require 1.15.18

For the Ad Astra Giselle Addon, it seems you have version 6.5, so you should probably install version [5.8](https://modrinth.com/mod/ad-astra-giselle-addon/version/5.8).

For Ad Astra Delight, sadly, version 1.0.0 is the only one that requires any version, which that one only adds the cheese sandwich.

But don't worry. Soon, I'll make this mod for ad astra versions 1.15.18 and up. See the [status](https://github.com/DRD2k8/ad_extendra/wiki/Status) for more info.
