### ISSUE TITLE
Server side only crash

### ISSUE THREAD

**Issue by Mysticpasta1** [DRD2k8/ad_extendra#6]
when starting a server with ad extendra I got a crash report

[crash-2024-09-27_10.36.23-fml.txt](https://github.com/user-attachments/files/17176114/crash-2024-09-27_10.36.23-fml.txt)

**Comment by DRD2k8** [comment]
This issue seems to only be on the forge version. The fabric version of the mod has split sources. But this should be fixed on 1.0.3 or 1.1.0.

v1.1.0 of this mod will be for Ad Astra versions 1.15.18+.

v1.0.3 of this mod might be the last version before moving to another Ad Astra version.

**Comment by Mysticpasta1** [comment]
is it going to be out soon?

**Comment by DRD2k8** [comment]
Yes.

**Comment by DRD2k8** [comment]
I finished [v1.1.0](https://modrinth.com/mod/ad_extendra-continuation/version/1.1.0). But I'm not sure about doing v1.0.3 yet.
